# Generated by Django 5.2 on 2026-04-15 22:15

import apps.clients.models
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('client_type', models.CharField(choices=[('LEGAL', 'حقوقی'), ('REAL', 'حقیقی')], max_length=10, verbose_name='نوع مشتری')),
                ('client_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='کد مشتری')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='سقف اعتبار (ریال)')),
                ('used_credit', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=20, verbose_name='اعتبار مصرف شده (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('portal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر پرتال')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ClientBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('account_number', models.CharField(max_length=30, verbose_name='شماره حساب')),
                ('sheba', models.CharField(blank=True, max_length=26, validators=[apps.core.validators.validate_sheba], verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, verbose_name='شماره کارت')),
                ('is_primary', models.BooleanField(default=False, verbose_name='حساب اصلی')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='clients.client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('contact_type', models.CharField(choices=[('PHONE', 'تلفن'), ('EMAIL', 'ایمیل'), ('FAX', 'فکس'), ('ADDRESS', 'آدرس')], max_length=10, verbose_name='نوع تماس')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doc_type', models.CharField(choices=[('NATIONAL_CARD', 'کارت ملی'), ('REGISTRATION_CERT', 'گواهی ثبت'), ('ARTICLES_OF_ASSOCIATION', 'اساسنامه'), ('FINANCIAL_STATEMENT', 'صورت\u200cهای مالی'), ('TAX_CLEARANCE', 'مفاصا حساب مالیاتی'), ('OFFICIAL_GAZETTE', 'روزنامه رسمی'), ('POWER_OF_ATTORNEY', 'وکالت\u200cنامه'), ('OTHER', 'سایر')], max_length=30, verbose_name='نوع مدرک')),
                ('file', models.FileField(upload_to=apps.clients.models.client_document_path, validators=[apps.core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'], message='فرمت فایل مجاز نیست. فرمت\u200cهای مجاز: pdf, jpg, jpeg, png, docx')], verbose_name='فایل')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'مدرک مشتری',
                'verbose_name_plural': 'مدارک مشتری',
            },
        ),
        migrations.CreateModel(
            name='LegalPersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='شماره ثبت')),
                ('national_id', models.CharField(blank=True, max_length=11, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت')),
                ('ceo_name', models.CharField(blank=True, max_length=255, verbose_name='نام مدیرعامل')),
                ('ceo_national_code', models.CharField(blank=True, max_length=10, validators=[apps.core.validators.validate_iranian_national_code], verbose_name='کد ملی مدیرعامل')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='clients.client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی',
                'verbose_name_plural': 'پروفایل\u200cهای حقوقی',
            },
        ),
        migrations.CreateModel(
            name='RealPersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('national_code', models.CharField(max_length=10, validators=[apps.core.validators.validate_iranian_national_code], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_profile', to='clients.client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پروفایل حقیقی',
                'verbose_name_plural': 'پروفایل\u200cهای حقیقی',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'),
        ),
    ]
