# Generated by Django 5.2 on 2026-04-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('guarantees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='نام ذینفع')),
                ('beneficiary_info', models.TextField(blank=True, verbose_name='اطلاعات ذینفع')),
                ('requested_amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ درخواستی (ریال)')),
                ('purpose', models.TextField(verbose_name='موضوع')),
                ('requested_duration_months', models.PositiveIntegerField(default=12, verbose_name='مدت درخواستی (ماه)')),
                ('status', models.CharField(choices=[('SUBMITTED', 'ارسال شده'), ('UNDER_REVIEW', 'در حال بررسی'), ('CONVERTED', 'تبدیل شده'), ('REJECTED', 'رد شده')], default='SUBMITTED', max_length=20, verbose_name='وضعیت')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='یادداشت بررسی\u200cکننده')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_requests', to='clients.client', verbose_name='مشتری')),
                ('converted_to_guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه تبدیل\u200cشده')),
                ('guarantee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guarantees.guaranteetype', verbose_name='نوع ضمانت\u200cنامه')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='ارسال شده توسط')),
            ],
            options={
                'verbose_name': 'درخواست ضمانت\u200cنامه',
                'verbose_name_plural': 'درخواست\u200cهای ضمانت\u200cنامه',
                'ordering': ['-created_at'],
            },
        ),
    ]
