# Generated by Django 5.2 on 2026-04-15 22:15

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('template_type', models.CharField(choices=[('GUARANTEE_LETTER', 'نامه ضمانت\u200cنامه'), ('CONTRACT', 'قرارداد'), ('RECEIPT', 'رسید'), ('FEE_STATEMENT', 'صورتحساب'), ('OTHER', 'سایر')], max_length=30, verbose_name='نوع قالب')),
                ('format', models.CharField(choices=[('HTML', 'HTML (برای PDF)'), ('DOCX', 'DOCX (قالب Word)')], max_length=10, verbose_name='فرمت')),
                ('file', models.FileField(blank=True, upload_to='templates/', verbose_name='فایل قالب (DOCX)')),
                ('template_content', models.TextField(blank=True, verbose_name='محتوای قالب (HTML)')),
                ('variables_schema', models.JSONField(blank=True, default=dict, help_text='JSON شامل متغیرهای مورد انتظار قالب', verbose_name='متغیرهای قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قالب سند',
                'verbose_name_plural': 'قالب\u200cهای اسناد',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('contract_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='شماره قرارداد')),
                ('contract_type', models.CharField(choices=[('GUARANTEE_ISSUANCE', 'صدور ضمانت\u200cنامه'), ('FRAMEWORK', 'قرارداد چارچوب'), ('AMENDMENT', 'اصلاحیه')], max_length=30, verbose_name='نوع قرارداد')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('total_value', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ارزش کل (ریال)')),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('COMPLETED', 'تکمیل شده'), ('TERMINATED', 'فسخ شده')], default='DRAFT', max_length=50, verbose_name='وضعیت')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('signed_by_client', models.BooleanField(default=False, verbose_name='امضای مشتری')),
                ('signed_by_director', models.BooleanField(default=False, verbose_name='امضای مدیر')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doc_type', models.CharField(choices=[('ORIGINAL', 'نسخه اصلی'), ('AMENDMENT', 'اصلاحیه'), ('APPENDIX', 'پیوست')], max_length=20, verbose_name='نوع سند')),
                ('file', models.FileField(upload_to='contracts/documents/', validators=[apps.core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'], message='فرمت فایل مجاز نیست. فرمت\u200cهای مجاز: pdf, jpg, jpeg, png, docx')], verbose_name='فایل')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'سند قرارداد',
                'verbose_name_plural': 'اسناد قرارداد',
            },
        ),
    ]
