# Generated by Django 5.2 on 2026-04-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع گزارش')),
                ('data', models.JSONField(default=dict, verbose_name='داده')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تولید')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='پارامترها')),
            ],
            options={
                'verbose_name': 'اسنپ\u200cشات داشبورد',
                'verbose_name_plural': 'اسنپ\u200cشات\u200cهای داشبورد',
            },
        ),
    ]
