# Generated by Django 5.2 on 2026-04-15 22:15

import apps.collaterals.models
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('collateral_type', models.CharField(choices=[('REAL_ESTATE', 'ملک'), ('BANK_DEPOSIT', 'سپرده بانکی'), ('CHECK', 'چک'), ('PROMISSORY_NOTE', 'سفته'), ('STOCK', 'سهام'), ('EQUIPMENT', 'تجهیزات'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع وثیقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('estimated_value', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='ارزش تخمینی (ریال)')),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='ارزش کارشناسی (ریال)')),
                ('appraisal_date', models.DateField(blank=True, null=True, verbose_name='تاریخ کارشناسی')),
                ('status', models.CharField(choices=[('AVAILABLE', 'آزاد'), ('PLEDGED', 'در رهن'), ('RELEASED', 'آزاد شده'), ('SEIZED', 'توقیف شده')], default='AVAILABLE', max_length=20, verbose_name='وضعیت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='clients.client', verbose_name='مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'وثیقه',
                'verbose_name_plural': 'وثایق',
            },
        ),
        migrations.CreateModel(
            name='CollateralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doc_type', models.CharField(max_length=100, verbose_name='نوع مدرک')),
                ('file', models.FileField(upload_to=apps.collaterals.models.collateral_document_path, validators=[apps.core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'], message='فرمت فایل مجاز نیست. فرمت\u200cهای مجاز: pdf, jpg, jpeg, png, docx')], verbose_name='فایل')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collaterals.collateral', verbose_name='وثیقه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'مدرک وثیقه',
                'verbose_name_plural': 'مدارک وثیقه',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('pledged_amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ رهن (ریال)')),
                ('pledged_date', models.DateField(auto_now_add=True, verbose_name='تاریخ رهن')),
                ('released_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آزادسازی')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_collaterals', to='collaterals.collateral', verbose_name='وثیقه')),
            ],
            options={
                'verbose_name': 'وثیقه ضمانت\u200cنامه',
                'verbose_name_plural': 'وثایق ضمانت\u200cنامه\u200cها',
            },
        ),
    ]
