# Generated by Django 5.2 on 2026-04-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaterals', '0001_initial'),
        ('guarantees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteecollateral',
            name='guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_collaterals', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه'),
        ),
        migrations.AlterUniqueTogether(
            name='guaranteecollateral',
            unique_together={('guarantee', 'collateral')},
        ),
    ]
