# Generated by Django 5.2 on 2026-04-15 22:15

import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('creditframework', '0001_initial'),
        ('guarantees', '0001_seed_guarantee_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('beneficiary_type', models.CharField(choices=[('GOVERNMENT', 'دولتی'), ('PRIVATE', 'خصوصی'), ('BANK', 'بانک'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع ذینفع')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='شناسه ملی / کد ملی')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='شماره ثبت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='نام رابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ذینفع',
                'verbose_name_plural': 'ذینفعان',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('default_commission_rate', models.DecimalField(decimal_places=4, help_text='مثال: 0.0150 = 1.5%', max_digits=5, verbose_name='نرخ کارمزد پیش\u200cفرض')),
                ('default_deposit_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5, verbose_name='نسبت سپرده پیش\u200cفرض')),
                ('typical_duration_months', models.PositiveIntegerField(default=12, verbose_name='مدت معمول (ماه)')),
                ('requires_collateral', models.BooleanField(default=True, verbose_name='نیاز به وثیقه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع ضمانت\u200cنامه',
                'verbose_name_plural': 'انواع ضمانت\u200cنامه',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('guarantee_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='شماره ضمانت\u200cنامه')),
                ('state', django_fsm.FSMField(choices=[('draft', 'پیش\u200cنویس'), ('under_review', 'در حال بررسی'), ('approved', 'تأیید شده'), ('issued', 'صادر شده'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'ابطال شده'), ('claimed', 'مطالبه شده')], default='draft', max_length=50, protected=True, verbose_name='وضعیت')),
                ('framework_status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PASS', 'تأیید'), ('BLOCKED', 'مسدود'), ('OVERRIDDEN', 'بازنگری مدیر')], default='PENDING', max_length=20, verbose_name='وضعیت چارچوب اعتباری')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ (ریال)')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('purpose', models.TextField(blank=True, verbose_name='موضوع / شرح')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ سپرده (ریال)')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, verbose_name='نرخ کارمزد')),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ کارمزد (ریال)')),
                ('renewal_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تمدید')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد / بازگشت')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='guarantees.beneficiary', verbose_name='ذینفع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='clients.client', verbose_name='مشتری')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='contracts.contract', verbose_name='قرارداد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('credit_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='creditframework.creditevaluation', verbose_name='ارزیابی اعتباری')),
                ('parent_guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه مادر (تمدید)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بررسی کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
                ('guarantee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='guarantees.guaranteetype', verbose_name='نوع ضمانت\u200cنامه')),
            ],
            options={
                'verbose_name': 'ضمانت\u200cنامه',
                'verbose_name_plural': 'ضمانت\u200cنامه\u200cها',
                'permissions': [('can_submit_guarantee', 'ارسال ضمانت\u200cنامه برای بررسی'), ('can_approve_guarantee', 'تأیید ضمانت\u200cنامه'), ('can_issue_guarantee', 'صدور ضمانت\u200cنامه'), ('can_cancel_guarantee', 'ابطال ضمانت\u200cنامه')],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('fee_type', models.CharField(choices=[('COMMISSION', 'کارمزد'), ('STAMP_DUTY', 'حق تمبر'), ('SERVICE_FEE', 'هزینه خدمات'), ('RENEWAL_FEE', 'هزینه تمدید')], max_length=20, verbose_name='نوع هزینه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ (ریال)')),
                ('calculation_basis', models.TextField(blank=True, verbose_name='مبنای محاسبه')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه')),
            ],
            options={
                'verbose_name': 'جدول هزینه',
                'verbose_name_plural': 'جدول هزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('letter_number', models.CharField(max_length=30, unique=True, verbose_name='شماره نامه')),
                ('letter_date', models.DateField(verbose_name='تاریخ نامه')),
                ('template_used', models.CharField(blank=True, max_length=100, verbose_name='قالب مورد استفاده')),
                ('generated_pdf', models.FileField(blank=True, upload_to='guarantee_letters/pdf/', verbose_name='فایل PDF')),
                ('generated_docx', models.FileField(blank=True, upload_to='guarantee_letters/docx/', verbose_name='فایل DOCX')),
                ('is_signed', models.BooleanField(default=False, verbose_name='امضا شده')),
                ('guarantee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='امضا کننده')),
            ],
            options={
                'verbose_name': 'نامه ضمانت\u200cنامه',
                'verbose_name_plural': 'نامه\u200cهای ضمانت\u200cنامه',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('source_state', models.CharField(max_length=20, verbose_name='وضعیت مبدأ')),
                ('target_state', models.CharField(max_length=20, verbose_name='وضعیت مقصد')),
                ('comment', models.TextField(blank=True, verbose_name='توضیحات')),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه')),
                ('transitioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
            ],
            options={
                'verbose_name': 'تغییر وضعیت ضمانت\u200cنامه',
                'verbose_name_plural': 'تغییرات وضعیت ضمانت\u200cنامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'سپرده'), ('COMMISSION', 'کارمزد'), ('REFUND', 'بازپرداخت'), ('RENEWAL_FEE', 'هزینه تمدید')], max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ (ریال)')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'انتقال بانکی'), ('CHECK', 'چک'), ('CASH', 'نقدی'), ('ONLINE', 'آنلاین')], max_length=20, verbose_name='روش پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='مشتری')),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='guarantees.feeschedule', verbose_name='ردیف هزینه')),
                ('guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['client', 'state'], name='guarantees__client__f4fb87_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['expiry_date'], name='guarantees__expiry__614997_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['state'], name='guarantees__state_fdb7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['framework_status'], name='guarantees__framewo_a9f3b4_idx'),
        ),
    ]
