# Generated by Django 5.2 on 2026-04-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('raw_value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='مقدار خام')),
                ('normalized_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='امتیاز نرمال (0-100)')),
                ('weighted_score', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='امتیاز وزنی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'جزئیات ارزیابی',
                'verbose_name_plural': 'جزئیات ارزیابی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CreditTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام سطح')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='حداقل امتیاز')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='حداکثر امتیاز')),
                ('max_credit_limit', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='سقف اعتبار (ریال)')),
                ('max_single_guarantee_pct', models.DecimalField(decimal_places=2, default=40, help_text='حداکثر درصد از سقف اعتبار برای یک ضمانت\u200cنامه', max_digits=5, verbose_name='حداکثر درصد تک ضمانت\u200cنامه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سطح اعتباری',
                'verbose_name_plural': 'سطوح اعتباری',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='DirectorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('override_reason', models.TextField(verbose_name='دلیل بازنگری')),
                ('granted_credit_limit', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='سقف اعتبار اعطایی (ریال)')),
                ('override_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازنگری')),
                ('expiry_date', models.DateField(blank=True, help_text='خالی = بدون محدودیت زمانی', null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'بازنگری مدیر',
                'verbose_name_plural': 'بازنگری\u200cهای مدیر',
                'ordering': ['-override_date'],
            },
        ),
        migrations.CreateModel(
            name='ScorecardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته امتیازدهی',
                'verbose_name_plural': 'دسته\u200cهای امتیازدهی',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ScorecardFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name_fa', models.CharField(max_length=150, verbose_name='نام عامل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('weight', models.DecimalField(decimal_places=2, help_text='مجموع وزن\u200cها باید ۱۰۰ باشد', max_digits=5, verbose_name='وزن')),
                ('value_type', models.CharField(choices=[('NUMERIC', 'عددی'), ('PERCENTAGE', 'درصدی'), ('ENUM', 'انتخابی'), ('BOOLEAN', 'بله / خیر')], max_length=20, verbose_name='نوع مقدار')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='حداقل مقدار')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='حداکثر مقدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عامل امتیازدهی',
                'verbose_name_plural': 'عوامل امتیازدهی',
            },
        ),
        migrations.CreateModel(
            name='ScorecardFactorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('label_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'گزینه عامل',
                'verbose_name_plural': 'گزینه\u200cهای عامل',
            },
        ),
        migrations.CreateModel(
            name='CreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارزیابی')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='امتیاز کل')),
                ('recommended_credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='سقف اعتبار پیشنهادی (ریال)')),
                ('status', models.CharField(choices=[('PASS', 'تأیید'), ('FAIL', 'رد'), ('OVERRIDDEN', 'بازنگری مدیر')], default='PASS', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, help_text='آخرین ارزیابی فعال برای هر مشتری', verbose_name='ارزیابی فعال')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_evaluations', to='clients.client', verbose_name='مشتری')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ارزیاب')),
            ],
            options={
                'verbose_name': 'ارزیابی اعتباری',
                'verbose_name_plural': 'ارزیابی\u200cهای اعتباری',
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
