# Generated by Django 5.2 on 2026-04-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditframework', '0001_initial'),
        ('guarantees', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditevaluation',
            name='guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_evaluations_direct', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه'),
        ),
        migrations.AddField(
            model_name='creditevaluationdetail',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='creditframework.creditevaluation', verbose_name='ارزیابی'),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='assigned_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='creditframework.credittier', verbose_name='سطح اختصاص\u200cیافته'),
        ),
        migrations.AddField(
            model_name='directoroverride',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='creditframework.creditevaluation', verbose_name='ارزیابی'),
        ),
        migrations.AddField(
            model_name='directoroverride',
            name='guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='guarantees.guarantee', verbose_name='ضمانت\u200cنامه'),
        ),
        migrations.AddField(
            model_name='directoroverride',
            name='original_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='creditframework.credittier', verbose_name='سطح اصلی'),
        ),
        migrations.AddField(
            model_name='directoroverride',
            name='overridden_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بازنگری توسط'),
        ),
        migrations.AddField(
            model_name='scorecardfactor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='creditframework.scorecardcategory', verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='creditevaluationdetail',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='creditframework.scorecardfactor', verbose_name='عامل'),
        ),
        migrations.AddField(
            model_name='scorecardfactoroption',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='creditframework.scorecardfactor', verbose_name='عامل'),
        ),
    ]
